{{- if .Values.environments -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
data:
{{- range $k, $v := .Values.environments }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end -}}