{{- with .Values.persistentVolumes -}}
{{- range . }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: {{ $.Values.namespace | default "default" }}
    name: {{ include "app.fullname" $ }}-{{ .name }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .efsID }}
    volumeAttributes:
      encryptInTransit: "false"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "app.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
{{- end -}}
{{- end -}}
