{{- with .Values.persistentVolumes -}}
{{- range . }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace | default "default" }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .size | default "5G" }}
---
{{- end -}}
{{- end -}}
