{{- if .Values.awsSecrets -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ include "app.secretsProviderName" . }}
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook-weight": "-1"
spec:
  parameters:
    objects: |
      {{- range .Values.awsSecrets }}
      - objectAlias: {{ .objectAlias | quote }}
        objectType: "secretsmanager"
        objectName: {{ .objectName | quote  }}
      {{- end }}
      
  provider: aws
  secretObjects:
    - data:
       {{- range .Values.awsSecrets }}
        - key: {{ .objectAlias | quote }}
          objectName: {{ .objectAlias | quote }}
        {{- end }}
      secretName: {{ include "app.secretsProviderName" . }}
      type: Opaque
{{- end -}}